name: Rust Linux

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        rust: [nightly]

    steps:
      - uses: actions/checkout@v2
      - name: Install nightly
        run: rustup toolchain install nightly
      - name: add aarch64
        run: rustup target add aarch64-unknown-linux-gnu
      - name: add arm 7
        run: rustup target add armv7-unknown-linux-gnueabihf
      - name: Build
        run: cargo +nightly build --release  --target=x86_64-unknown-linux-gnu
      - name: Build arm 7
        run:  cargo +nightly build --release --target=armv7-unknown-linux-gnueabihf
      - name: Build aarch64
        run:  cargo +nightly build --release --target=aarch64-unknown-linux-gn
      - name: Rename
        run: mv ./target/x86_64-unknown-linux-gnu/release/izzy target/release/izzy_linux  && mv ./target/aarch64-unknown-linux-gnu/release/izzy target/release/izzy_linux-arm64v8 
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            target/release/izzy_linux
            target/release/izzy_linux-arm64v8
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
